### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by hiyoko3** [narugit/Memoma#1]
# Todo

## Module
- [x] 新規プロジェクト作成時のバグFix
- [x] Ctrl+S による全保存機能の実装
- [ ] url押したらデフォルトブラウザ起動

## UI / UX
- [x] デザイン
- [x] UX

# 役割

- Module => @narugit 
- UI => @hIyoko3

**Comment by hiyoko3** [comment]
Tasks were done.

**Comment by narugit** [comment]
urlでブラウザ起動は優先度低いのでひとまずclose
