### ISSUE TITLE
import の変数名重複エラー

### ISSUE THREAD

**Issue by hiyoko3** [narugit/Memoma#6]
importしたファイルのコンパイル時にはファイル名が自動的に決定する。

この時、ファイル名が重複してエラーが出る

例
example1.ts
```
import { ipcRenderer } from 'electron';
```

example2.ts
```
import { ipcRenderer  as hogeIpc } from 'electron';
```

この時、コンパイルされると

example1.js
```
const electron_1 = require('electron');
const ipcRenderer = electron_1.ipcRenderer;
```

example2.js
```
const electron_1 = require('electron');
const hogeIpc = electron_1.ipcRenderer;
```

となり、同じ変数名(`electron_1`)が出力されているためエラーが発生する。

**Comment by narugit** [comment]
`require`でelectronモジュールを読み込み、異なる変数名を割り当てることにより、コンパイル後に同一変数名にならなくなりました。

ご確認お願いいたします。

**Comment by hiyoko3** [comment]
解決したので閉じます
